version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000/tcp
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: "exit 0"

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 4321:5432
    env_file:
      - .env
    healthcheck:
      test: "exit 0"
