version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000/tcp
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - ./.env
    ports:
      - 4321:5432
    healthcheck:
      test: "exit 0"

volumes:
  postgres_data:
